name: Deploy to Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build docker image
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: docker build -t ghcr.io/uniquenetwork/unique-marketplace-checkout-frontend/checkout-market-front:dev . -f .docker/Dockerfile
      - name: Push to GitHub Registry
        run: docker push ghcr.io/uniquenetwork/unique-marketplace-checkout-frontend/checkout-market-front:dev

  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - run: docker stack deploy -c .github/services/dev.yml ${{ secrets.DOCKER_NETWORK }}        
